services:
  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  networkdb:
    image: postgres:alpine
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    environment:
      - POSTGRES_USER=networkdbuser
      - POSTGRES_PASSWORD=networkdbpassword
    healthcheck:
      test: ["CMD-SHELL","pg_isready"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 10s
  # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # #

  serverdb:
    image: redis:alpine
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    # volumes:
    #   - serverdb:/data
    environment:
      - REDIS_ARGS=--save 5 1
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL","redis-cli ping | grep -q PONG || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 10s

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:serverdb:6379
    ports:
      - "8081:8081"
    depends_on:
      - serverdb

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  pdf-frontend:
    build: 
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    # bind my ~/.ssh/id_ed25519 to the container in read only mode
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    ports:
      - "3000:3000"
    # volumes:
    #   - ./static/pdf-test:/app/pdfs
    environment:
    - NETWORKDB_HOST=networkdb
    - NETWORKDB_PASSWORD=networkdbpassword
    - NETWORKDB_USER=networkdbuser
    - SERVERDB_HOST=serverdb
    - REDIS_HOST=serverdb